name: Build e Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.19.0

      - name: Instalar dependências do Frontend
        working-directory: ./frontend
        run: npm install

      - name: Build do Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Iniciar agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
  ssh-private-key: ${{ secrets.Secret_SSH }}

      - name: Limpar arquivos antigos no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            rm -f /var/www/authapiphp/authapi/public/index.html
            rm -rf /var/www/authapiphp/authapi/public/assets
          EOF

      - name: Enviar novos arquivos para o servidor
        run: |
          scp -r ./frontend/dist/index.html ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/authapiphp/authapi/public/
          scp -r ./frontend/dist/assets ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/authapiphp/authapi/public/
